spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hope_saas_bfs_XXX?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  redis:
    # TODO: 需要改写为本地环境或者开发环境的Redis地址
    host: 127.0.0.1
    port: 6379

  kafka:
    # XXX: 默认配置为【开发环境 - 所有业务线公用】的自建kafka的地址，如无特殊需求，建议不要改动该配置项
    bootstrap-servers: [52.83.139.213:9092]
    consumer:
      group-id: ${spring.application.id}_local